update config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -123,14 +123,14 @@ jobs:
             name: Install tar utility
             command: |
               yum install -y tar gzip
-        - run:
-            name: Create BE Cloudformation Stack
-            command: |
-              aws cloudformation deploy \
-                --template-file .circleci/files/backend.yml \
-                --tags project=Udacity \
-                --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
-                --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+        # - run:
+        #     name: Create BE Cloudformation Stack
+        #     command: |
+        #       aws cloudformation deploy \
+        #         --template-file .circleci/files/backend.yml \
+        #         --tags project=Udacity \
+        #         --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+        #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
         # - run:
         #     name: Create FE Cloudformation Stack
         #     command: |
@@ -139,16 +139,16 @@ jobs:
         #         --tags project=Udacity \
         #         --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
         #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
-        - run:
-            name: Add back-end ip to ansible inventory
-            command: |
-                echo [web] > ~/inventory.txt
-                aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory.txt
         # - run:
         #     name: Add back-end ip to ansible inventory
         #     command: |
         #         echo [web] > ~/inventory.txt
-        #         echo 18.206.176.2 >> ~/inventory.txt
+        #         aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory.txt
+        - run:
+            name: Add back-end ip to ansible inventory
+            command: |
+                echo [web] > ~/inventory.txt
+                echo 52.23.213.243 >> ~/inventory.txt
         - persist_to_workspace:
             root: ~/
             paths:
@@ -173,6 +173,23 @@ jobs:
           name: Run Playbook and Configure server
           command:  |
             ansible-playbook -i ~/inventory.txt .circleci/ansible/configure-server.yml
+
+  # run-migrations:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  #     - run:
+  #         name: Send migration results to memstash
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  #    # Here's where you will add some code to rollback on failure
 
 workflows:
   default:
